<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>WindowsDesktop</RootNamespace>
    <AssemblyName>VirtualDesktop.WPF</AssemblyName>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Release'">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591</NoWarn>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VirtualDesktop\VirtualDesktop.csproj" />
  </ItemGroup>
</Project>
